server:
  port: 8081
spring:
  application:
    name: cicledianping
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/circledp?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: admin
# redis
  redis:
    host: 175.178.252.65
    port: 6379
    password: fangshaolei123
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.circle.entiry # 别名扫描
logging:
  level:
    com.circle: debug
